### PR TITLE
Remove and use utitilies that are now in openshift.

### LINKED ISSUE #26: Move configMap utilities to thoth.common
**Is your feature request related to a problem? Please describe.**
We now have code in mi-scheduler for acquiring data from ConfigMap.

**Describe the solution you'd like**
This functionality should be moved to `common`because it has to do more with openshift than actual scheduling

**Additional context**
See https://github.com/thoth-station/mi-scheduler/pull/25#discussion_r456366467 for more details

### PR DESCRIPTION
**Pull request by xtuchyna**
## Related Issues and Dependencies
This PR fixes #26 and requires https://github.com/thoth-station/common/pull/1037 

## This introduces a breaking change

- [ ] Yes
- [X] No

## This Pull Request implements
Remove utitilites that are now in openshift.

### CODE REVIEW

**Review by pacospace — APPROVED** [review]
lgtm!

**Comment by xtuchyna** [comment]
hello hello @pacospace is it still alright?

**Review by pacospace — APPROVED** [review]
Thanks!!

**Comment by pacospace** [comment]
> hello hello @pacospace is it still alright?

sorry for delay @xtuchyna, I thought I approved it already :)

**Comment by xtuchyna** [comment]
> > hello hello @pacospace is it still alright?
> 
> sorry for delay @xtuchyna, I thought I approved it already :)

I've made a couple of lil changes after approval :)

**Pull request merged**
