### PR TITLE
Add create_knowledge param for GH-related workflows

### PR DESCRIPTION
**Pull request by xtuchyna**
## Related Issues and Dependencies
Related to https://github.com/thoth-station/common/pull/1234
https://github.com/thoth-station/thoth-application/issues/1835

## This introduces a breaking change

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by meile18 — APPROVED** [review]
LGTM :+1:

**Review by harshad16 — APPROVED** [review]
lgtm
thank :100:

**Pull request merged**
