### PR TITLE
Change knowledge path to mi, add merge path for merge job

### LINKED ISSUE #188: Re-use present MI data for kebechet analysis
**Is your feature request related to a problem? Please describe.**
PullRequests and Issues are now aggregated separately, in spite having a clear intersection between the ordinar *MI* analysis data. 

**Describe the solution you'd like**
Merge these two locations to only have *MI* data storage, and kebechet analysis with scores in different location.

**Describe alternatives you've considered**

**Additional context**
This would however require to remove the duplicate data aggregation workflows for repositories that both use kebechet AND are scheduled for regular *MI* aggregation.

Nevertheless, this can be added on top of the working solution, because although this introduces useless operation, its resource cost is not that big (the second duplicate workflow would just check if the data is up to date - and considering the aggregation is running in the same day, there won't be that much new data)

/kind feature

### PR DESCRIPTION
**Pull request by xtuchyna**
## Related Issues and Dependencies
Closes #188 

## This introduces a breaking change

- [ ] Yes
- [X] No

## This Pull Request implements
Reuse data from mi aggregation

## Description
/hold until changes to common are made

### CODE REVIEW

**Comment by goern** [comment]
ping

**Review by pacospace — COMMENTED** [review]
lgtm!

**Comment by xtuchyna** [comment]
uh oh!

/approve

**Pull request merged**
